### ISSUE TITLE
Why have you used the pascal case naming convention?

### ISSUE THREAD

**Issue by ElectroluxV2** [bonan/dbus-ts#1]
Example from the README:
```ts
const [units] = await systemd.ListUnits()
```
Why not?
```ts
const [units] = await systemd.listUnits()
```
Do you need help with the unification to the camel case, or is there reasoning behind it?

**Comment by bonan** [comment]
I did not chose the naming convention, the [systemd D-Bus API](https://www.freedesktop.org/wiki/Software/systemd/dbus/) has this convention.

Methods are generated at runtime by fetching exported APIs from D-Bus.

I think it would cause more confusion and potentially bugs to try to convert these to camel case at runtime.
[Other D-Bus implementations](https://github.com/sidorares/node-dbus) do the same thing.

You could always write your code like this to signify that it's a dynamic method:
```typescript
const [units] = await systemd["ListUnits"]()
```

**Comment by ElectroluxV2** [comment]
It makes sense; thanks for the suggestion. I will use bracket notation.
